### ISSUE TITLE
Tempus is missing

### ISSUE THREAD

**Issue by TATDK** [ythri/tcresearch#1]

**Comment by ythri** [comment]
Strange, I can find Tempus neither in the official [Thaumcraft API](https://github.com/Azanor/thaumcraft-api/blob/master/aspects/Aspect.java), nor in the [research connecting chart](http://www.reddit.com/r/feedthebeast/comments/1y87fn/thaumcraft_4_research_connecting_chart/) posted on reddit. Are you sure tempus is still a valid aspect and has not been removed in Thaumcraft 4.1? If yes, can you tell me what it is made of? Thanks

**Comment by TATDK** [comment]
My bad, it's added by Magic Bees.
Perhaps add support for addon mods?

**Comment by ythri** [comment]
Ok, I finally added all mod aspects that I know of: tempus from magic bees and a few others from forbidden magic.
