### ISSUE TITLE
Senses -> Ordo gives wrong result

### ISSUE THREAD

**Issue by jdratlif** [ythri/tcresearch#11]
Senses -> Ordo connects using Tempestas to Gelum to Ordo in 3 min connections, but Gelum doesn't have tempestas. It has ordo and aqua. So you need to connect tempestes to gelum with aqua. I am on 4.1.0g of Thaumcraft.

**Comment by ythri** [comment]
Actually, its the other way round, tempestas does use gelum. This was changed in 4.1.0g, because there was a clash in version 4.1.0f (with volatus, i believe).

**Comment by jdratlif** [comment]
Sorry. My mistake. I had a mod that was breaking thaumcraft aspects. I have fixed this now.
