### ISSUE TITLE
Aqua doesn't connect to Motus

### ISSUE THREAD

**Issue by jdratlif** [ythri/tcresearch#12]
The script wants to use aqua to get to Motus, but Motus doesn't have aqua in it. It's Aer and Ordo.

**Comment by dmitryk1** [comment]
I repair this but dont'know how put file in this project. It live at https://drive.google.com/file/d/0B6Vpwk37C-OlaHlFTWxNVjU5b1U/edit?usp=sharing

**Comment by ythri** [comment]
Motus was changed in Thaumcraft version 4.1.0f and now is the combination of Aer and Aqua. Please update your thaumcraft (if you have not already).

**Comment by jdratlif** [comment]
I'm using 4.1.0g, and in G, motus is aer and ordo.

**Comment by ythri** [comment]
Huh, that's strange. I will have a look at it over the weekend.

**Comment by jdratlif** [comment]
You can close this again. I had a mod with an outdated thaumcraft API which was breaking the aspect combos. Motus is aer + aqua. Sorry.
