### ISSUE TITLE
Tempestas doesn't connect to Gelum

### ISSUE THREAD

**Issue by ZacTheHac** [ythri/tcresearch#16]
Tempestas is comprised of Aer and Motus, and Gelum is Aqua and Ordo
While it makes sense to connect them, they don't, as of 4.1.0g
Side note: Tempestas has Motus, which itself has Aqua and Aer, but I don't think thaumcraft works recursively like that

**Comment by ythri** [comment]
Actually, tempestas was changed in 4.1.0g and now indeed uses gelum and aer instead of aqua and air. Did you try it ingame with the newest version? If so, I will have to check again as well.

**Comment by ZacTheHac** [comment]
I just checked: running 4.1.0g and it's showing Aer and motus. I do have thaumic tinkerer installed, could that be messing with the base aspects?

**Comment by Smashman** [comment]
Is this still an issue?

The 4.1.0g combinations we have have been verified.

**Comment by ythri** [comment]
I think the problem for a lot of people running 4.1.0g was that some mods still included the older Thaumcraft API. This reset the aspects to their older combinations. Hence, even when running 4.1.0g, you could have the old combination Tempestas = Aer + Motus, even though it should be Aer + Gelum. Nothing we can do about this sadly.

**Comment by Smashman** [comment]
I think we ought to lock this, then. It's not an issue that we can fix. Maybe we could put a note with a message similar to yours.
