### ISSUE TITLE
Layout is borked

### ISSUE THREAD

**Issue by MentalMouse** [ythri/tcresearch#20]
Since you updated to 4.1.1.9, the dropdown and selection lists are scrambles, and results appear frameless, at odd places blokcing the main display.

**Comment by radcom** [comment]
What browser are you using as I'm using the latest versions of Chrome & Firefox and it appears fine

**Comment by MentalMouse** [comment]
On 04/21/2014 09:46 AM, radcom wrote:

> What browser are you using as I'm using the latest versions of Chrome 
> & Firefox and it appears fine
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/ythri/tcresearch/issues/20#issuecomment-40936187.
> 
> Firefox under Ubuntu.  I'm attaching a screenshot, note the results 
> overlaid on the right column of the main grid.

```
 Thanks for your attention!
 Dave H.
```

**Comment by radcom** [comment]
For some reason your screen-shots aren't showing up could you repost them

**Comment by ythri** [comment]
Can't see the screenshots either. Please embed them or upload them somewhere else. Thanks.

**Comment by MentalMouse** [comment]
On 04/21/2014 03:48 PM, ythri wrote:

> Can't see the screenshots either. Please embed them or upload them 
> somewhere else. Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/ythri/tcresearch/issues/20#issuecomment-40969433.

OK, how about this?

Icons are disarranged, results are frameless over the main window.Also, 
the icons move away from underneath the cursor

**Comment by Smashman** [comment]
Please visit the actual Github website or link to images.

Clearly attaching them to an email reply does not work.

**Comment by Smashman** [comment]
I'm going to close this issue as neither @ythri nor I can reproduce this issue.

If you capture an image and inform us of the browser that you are using, feel free to reopen the issue.

Thank you.
