### ISSUE TITLE
Thaumcraft 4.2.2 new aspect combos

### ISSUE THREAD

**Issue by MentalMouse** [ythri/tcresearch#33]
As of 4.2.2, Cognitio is now ignis + spiritus, and Telum is now ignis + instrumentum.  It'd sure be nice if you could add another entry to the versions supported.

**Comment by MentalMouse** [comment]
And, I see that someone already did the necessary work -- not just on the aspects, but the help text as well:  https://github.com/ythri/tcresearch/pull/32 .  Now we just need ythri or someone else in charge to actually make it live.

**Comment by ythri** [comment]
Sorry for my long absence, I merge the pull request and the tool should again be up to date now.
