### ISSUE TITLE
Incorrect aspect combinations.

### ISSUE THREAD

**Issue by LKummer** [ythri/tcresearch#4]
The motion combination is incorrect, I think Azanor changed it in the last update of Thaumcraft. The code says the combination is Air and Order while the correct combination is Air and Water. I also found that the Weather combination was incorrect, the correct combination for Weather is Air and Motion.

**Comment by astamicu** [comment]
Arbor - Motus gives you Terra - Victus - Bestia. But Terra doesn't connect with Arbor. Herba does
If i try Motus - Arbor it's ok.

**Comment by ythri** [comment]
So, finally back at home. I will update the aspect combinations later today to the new Thaumcraft version. I got [this link](http://forum.feed-the-beast.com/threads/1-6-x-thaumcraft-4-0-5b-research-cheat-sheet-back-to-the-update-with-doc-succubism.32560/page-43#post-577129) sent to me, which should contain ALL changed combinations. Can you verify that these are indeed all the changes?

The aspect combinations so far are not incorrect (they were extracted from the sources as well), just for an older version.

**Comment by astamicu** [comment]
Oh, that's great. Thank you for you work :)

**Comment by ythri** [comment]
Ok, I updated the script to use the new aspect combinations of Thaumcraft 4.1.0g. Note that in this version, Tempestas has been changed again to Aer + Gelum, since Aer + Motus was a conflict with Volatus.
