### ISSUE TITLE
tcresearch

### ISSUE THREAD

**Issue by Roninangel** [ythri/tcresearch#6]
I would like to discuss with you the use of your script as part of an application I am developing.  Please email me at roninangel@yahoo.com to further the discussion.

Sincerely:

R0n1n Ang3l

**Comment by ythri** [comment]
I have a license note at the site, the script is available under [CC Attribution 4.0](http://creativecommons.org/licenses/by/4.0/). This means you can use everything as you please (e.g. commercial, modify it, whatever) as long as you link back to this repo. If you want, you can just fork this repository and afaik github will automatically show a link to the original version (this one). If you implement this thing with a different language anyway and don't use any of my code directly (looking and getting ideas is fine), you don't even have to link back or mention my name - I'm totally fine with this.

 If you have further questions, just comment, I will leave this issue open for now, Also, I would be interested in your application once its finished.

ythri

**Comment by Roninangel** [comment]
Thank you for getting back with me.  I am still in the early stages of the app.  I am still recruiting talent for the development team.  When i found your script I instantly new i wanted something like this for the Thaumcraft portion of the app.  It is going to be a multi-tier application that has add ons for each mod found in the FTB mod packs.  If you are interested in being part of the team let me know.  Other wise i will keep you in mind when I am looking for beta testers.  Thanks again for the quick response.

On Tuesday, March 11, 2014 2:39 PM, ythri notifications@github.com wrote:

I have a license note at the site, the script is available under CC Attribution 4.0. This means you can use everything as you please (e.g. commercial, modify it, whatever) as long as you link back to this repo. If you want, you can just fork this repository and afaik github will automatically show a link to the original version (this one). If you implement this thing with a different language anyway and don't use any of my code directly (looking and getting ideas is fine), you don't even have to link back or mention my name - I'm totally fine with this.
If you have further questions, just comment, I will leave this issue open for now, Also, I would be interested in your application once its finished.
ythri
